server:
  port: 8082
spring:
  application:
    name: spring-demo
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:generator/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
